# Generated by Django 3.0.7 on 2020-06-24 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('direction', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('cif', models.CharField(max_length=20)),
                ('hectares_available', models.CharField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
