# Generated by Django 3.0.7 on 2020-06-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='hectares_available',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
