# Generated by Django 3.0.7 on 2020-06-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0002_auto_20200624_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='sentinel_instance',
            field=models.CharField(default='96738ec4-8db4-452f-bf50-6ceee33c1c4e', max_length=255),
        ),
    ]
