# Generated by Django 3.0.7 on 2020-07-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0004_enterprise_hectares_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='hectares_used',
        ),
    ]
