# Generated by Django 3.0.7 on 2020-10-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0005_remove_enterprise_hectares_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='type_metric',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
