# Generated by Django 3.0.7 on 2020-11-03 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0001_initial'),
        ('enterprises', '0006_enterprise_type_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='cooperative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enterprises', to='cooperatives.Cooperative'),
        ),
    ]
