# Generated by Django 3.0.7 on 2023-12-13 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0007_enterprise_cooperative'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='continent',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='deleted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enterprise',
            name='is_monitor',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
