"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import datetime
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GDAL_LIBRARY_PATH = r'C:\OSGeo4W64\bin\gdal306'


# OSGeo4W
if os.name == 'nt':
    import platform
    OSGEO4W = r"C:\OSGeo4W"
    if '64' in platform.architecture()[0]:
        OSGEO4W += "64"
    assert os.path.isdir(OSGEO4W), "Directory does not exist: " + OSGEO4W
    os.environ['OSGEO4W_ROOT'] = OSGEO4W
    os.environ['GDAL_DATA'] = OSGEO4W + r"\share\epsg_csv"
    os.environ['PROJ_LIB'] = OSGEO4W + r"\share\proj"
    os.environ['PATH'] = OSGEO4W + r"\bin;" + os.environ['PATH']

os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'nr3x(2lfp=l@2c&&nmej6z5x(vb*v*j2f(%+s6@#3$(ivj$n^c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
}


ALLOWED_HOSTS = ['api-d4sf.smartbits-es.com', '127.0.0.1', 'localhost','api2-d4sf.smartbits-es.com']

CORS_ORIGIN_WHITELIST = (
    'http://localhost:8080',
    'https://localhost:8080',
    'http://localhost:8081',
    'https://192.168.1.55:8080',
    'http://192.168.1.55:8080',
    'http://api-d4sf.smartbits-es.com',
    'https://api-d4sf.smartbits-es.com',
    'http://api2-d4sf.smartbits-es.com',
    'https://api2-d4sf.smartbits-es.com',
    'http://d4smartfarming.smartbits-es.com',
    'https://d4smartfarming.smartbits-es.com',
    'http://d4smartfarming2.smartbits-es.com',
    'https://d4smartfarming2.smartbits-es.com',
)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'django_rest_passwordreset',
    'rest_framework_gis',
    'django.contrib.gis',
    'corsheaders',
    'employees',
    'roles',
    'groups',
    'parcelas',
    'user',
    'profiles',
    'enterprises',
    'imgprocess',
    'cooperatives',
    'newimgprocess',
    'campanas',
    'trazas',
]

import logging
import sys

# Configuración de registro para guardar los mensajes de la consola en un archivo
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',  # Puedes ajustar el nivel de registro aquí
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'archivo.log'),  # Nombre del archivo de registro
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',  # Puedes ajustar el nivel de registro aquí
            'propagate': True,
        },
    },
}

AUTH_USER_MODEL = 'user.User'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.IsAdminUser',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
    )
}
from datetime import timedelta
JWT_AUTH = {
    'JWT_ENCODE_HANDLER':
    'rest_framework_jwt.utils.jwt_encode_handler',
    'JWT_DECODE_HANDLER':
    'rest_framework_jwt.utils.jwt_decode_handler',
    'JWT_PAYLOAD_HANDLER':
    'rest_framework_jwt.utils.jwt_payload_handler',
    'JWT_PAYLOAD_GET_USER_ID_HANDLER':
    'rest_framework_jwt.utils.jwt_get_user_id_from_payload_handler',
    'JWT_RESPONSE_PAYLOAD_HANDLER':
    'rest_framework_jwt.utils.jwt_response_payload_handler',

    'JWT_SECRET_KEY': 'SECRET_KEY',
    'JWT_GET_USER_SECRET_KEY': None,
    'JWT_PUBLIC_KEY': None,
    'JWT_PRIVATE_KEY': None,
    'JWT_ALGORITHM': 'HS256',
    'JWT_VERIFY': True,
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_LEEWAY': 0,
    'JWT_EXPIRATION_DELTA': timedelta(days=30),
    'JWT_AUDIENCE': None,
    'JWT_ISSUER': None,
    'JWT_ALLOW_REFRESH': False,
    'JWT_REFRESH_EXPIRATION_DELTA': timedelta(days=30),
    'JWT_AUTH_HEADER_PREFIX': 'Bearer',
    'JWT_AUTH_COOKIE': None,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    # username 
    'backend.get_username.RequestMiddleware'
]

CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'backend.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'email')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
# django.contrib.gis.db.backends.postgis

# DEVELOP
DATABASES = {
    'default': {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": "dataforsmartfarming_testing_new",
        "USER": "dataforsmartfarmingbackend",
        "PASSWORD": "Cm&O8nOlKZlb",
        "HOST": "82.223.104.97",
        "PORT": "5432",
    },
    'secondary': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

#  MASTER
# DATABASES = {
#     'default': {
#         "ENGINE": "django.contrib.gis.db.backends.postgis",
#         "NAME": "dataforsmartfarming",
#         "USER": "dataforsmartfarmingbackend",
#         "PASSWORD": "Cm&O8nOlKZlb",
#         "HOST": "82.223.104.97",
#         "PORT": "5432",
#     },
#     'secondary': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# Email settings

EMAIL_HOST = 'smtp.strato.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'soporte@d4smartfarming.com'
EMAIL_HOST_PASSWORD = 'Ucbpablo01'
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True

# Sentinelsat settings
SENTINEL_CLIENT_ID = '33467c23-fada-4405-8a5b-33ee38169273'
SENTINEL_CLIENT_SECRET = '&O97/<>sWmmUrI2KctxxVf9iCQi*~eN|:I6R%o6:'

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

# STATIC_URL = '/static/'

MEDIA_URL = '/media/'
STATIC_URL = '/media/parcels/' # Prod: backend/media/parcels/
STATIC_ROOT = '/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/parcels')

# LOCAL
PARCEL_FOLDER = 'media/parcels/'  
SHAPES_FOLDER = 'media/shapes/' 
CAMPANA_FOLDER = 'media/campana/' 
RESULTADOS_FLODER = 'media/resultados_informes/'
SITE_URL = 'http://localhost:8080/'

# PROD
# PARCEL_FOLDER = 'backend/media/parcels/'
# SHAPES_FOLDER = 'backend/media/shapes/'
# CAMPANA_FOLDER = 'backend/media/campana/'
# RESULTADOS_FLODER = 'backend/media/resultados_informes/'
# SITE_URL = 'https://d4smartfarming2.smartbits-es.com/'