# Generated by Django 4.0.3 on 2022-03-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NdviMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('parcel', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('pix_azul_total', models.FloatField(blank=True, null=True)),
                ('pix_azul_total_porcent', models.FloatField(blank=True, null=True)),
                ('pix_azul_altos_total', models.FloatField(blank=True, null=True)),
                ('pix_azul_altos_porcent', models.FloatField(blank=True, null=True)),
                ('pix_azul_altos_area_porcent', models.FloatField(blank=True, null=True)),
                ('pix_azul_medios_total', models.FloatField(blank=True, null=True)),
                ('pix_azul_medios_porcent', models.FloatField(blank=True, null=True)),
                ('pix_azul_medios_area_porcent', models.FloatField(blank=True, null=True)),
                ('pix_azul_bajos_total', models.FloatField(blank=True, null=True)),
                ('pix_azul_bajos_porcent', models.FloatField(blank=True, null=True)),
                ('pix_azul_bajos_area_porcent', models.FloatField(blank=True, null=True)),
                ('pix_amarillo_total', models.FloatField(blank=True, null=True)),
                ('pix_amarillo_total_porcent', models.FloatField(blank=True, null=True)),
                ('pix_amarillo_altos_total', models.FloatField(blank=True, null=True)),
                ('pix_amarillo_altos_porcent', models.FloatField(blank=True, null=True)),
                ('pix_amarillo_altos_area_porcent', models.FloatField(blank=True, null=True)),
                ('pix_amarillo_medios_total', models.FloatField(blank=True, null=True)),
                ('pix_amarillo_medios_porcent', models.FloatField(blank=True, null=True)),
                ('pix_amarillo_medios_area_porcent', models.FloatField(blank=True, null=True)),
                ('pix_amarillo_bajos_total', models.FloatField(blank=True, null=True)),
                ('pix_amarillo_bajos_porcent', models.FloatField(blank=True, null=True)),
                ('pix_amarillo_bajos_area_porcent', models.FloatField(blank=True, null=True)),
                ('pix_rojo_total', models.FloatField(blank=True, null=True)),
                ('pix_rojo_total_porcent', models.FloatField(blank=True, null=True)),
                ('pix_rojo_altos_total', models.FloatField(blank=True, null=True)),
                ('pix_rojo_altos_porcent', models.FloatField(blank=True, null=True)),
                ('pix_rojo_altos_area_porcent', models.FloatField(blank=True, null=True)),
                ('pix_rojo_medios_total', models.FloatField(blank=True, null=True)),
                ('pix_rojo_medios_porcent', models.FloatField(blank=True, null=True)),
                ('pix_rojo_medios_area_porcent', models.FloatField(blank=True, null=True)),
                ('pix_rojo_bajos_total', models.FloatField(blank=True, null=True)),
                ('pix_rojo_bajos_porcent', models.FloatField(blank=True, null=True)),
                ('pix_rojo_bajos_area_porcent', models.FloatField(blank=True, null=True)),
                ('pix_verde_total', models.FloatField(blank=True, null=True)),
                ('pix_verde_total_porcent', models.FloatField(blank=True, null=True)),
                ('pix_verde_altos_total', models.FloatField(blank=True, null=True)),
                ('pix_verde_altos_porcent', models.FloatField(blank=True, null=True)),
                ('pix_verde_altos_area_porcent', models.FloatField(blank=True, null=True)),
                ('pix_verde_medios_total', models.FloatField(blank=True, null=True)),
                ('pix_verde_medios_porcent', models.FloatField(blank=True, null=True)),
                ('pix_verde_medios_area_porcent', models.FloatField(blank=True, null=True)),
                ('nubes_porcent', models.FloatField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
