# Generated by Django 4.0.3 on 2022-03-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndvimonitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndvimonitor',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ndvimonitor',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ndvimonitor',
            name='nubesImage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
