# Generated by Django 4.0.4 on 2022-04-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndvimonitor', '0002_ndvimonitor_date_ndvimonitor_image_and_more'),
        ('ndvimonitor', '0003_ndvimonitor_trueColorImage'),
    ]

    operations = [
    ]
