# Generated by Django 4.0.4 on 2022-04-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndvimonitor', '0004_merge_20220427_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndvimonitor',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
