# Generated by Django 3.0.7 on 2023-05-18 08:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.TextField()),
                ('app_name', models.TextField(default='Parcelas', null=True)),
                ('path', models.TextField(default='', null=True)),
                ('method', models.TextField(default='', null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'logs',
                'ordering': ['create_at'],
            },
        ),
    ]
