# Generated by Django 3.0.6 on 2020-06-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0002_auto_20200529_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='area',
            field=models.CharField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
