# Generated by Django 3.0.7 on 2020-06-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0003_parcel_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='enterprise_id',
            field=models.UUIDField(default='e20af9fa-892c-4099-9a5f-002e759d2948'),
        ),
    ]
