# Generated by Django 3.0.7 on 2020-07-17 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0005_remove_enterprise_hectares_used'),
        ('parcelas', '0004_parcel_enterprise_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='enterprise_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='enterprises.Enterprise'),
        ),
    ]
