# Generated by Django 3.0.7 on 2020-07-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0005_remove_enterprise_hectares_used'),
        ('parcelas', '0006_auto_20200717_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='enterprise',
        ),
        migrations.AddField(
            model_name='parcel',
            name='enterprise',
            field=models.ManyToManyField(to='enterprises.Enterprise'),
        ),
    ]
