# Generated by Django 3.0.7 on 2020-07-20 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0007_auto_20200720_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
