# Generated by Django 3.0.7 on 2020-07-20 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0008_parcel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='enterprise',
            new_name='enterprise_id',
        ),
    ]
