# Generated by Django 3.0.7 on 2020-07-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0005_remove_enterprise_hectares_used'),
        ('parcelas', '0010_auto_20200720_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='enterprise',
        ),
        migrations.AddField(
            model_name='parcel',
            name='enterprise_id',
            field=models.ManyToManyField(related_name='parcels', to='enterprises.Enterprise'),
        ),
    ]
