# Generated by Django 3.0.7 on 2020-07-20 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0005_remove_enterprise_hectares_used'),
        ('parcelas', '0011_auto_20200720_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='enterprise_id',
        ),
        migrations.AddField(
            model_name='parcel',
            name='enterprise',
            field=models.ForeignKey(default='178e5240-1a64-4631-a95d-a9a8f70f3305', on_delete=django.db.models.deletion.DO_NOTHING, related_name='parcels', to='enterprises.Enterprise'),
            preserve_default=False,
        ),
    ]
