# Generated by Django 3.0.7 on 2020-08-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0012_auto_20200720_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='area',
            field=models.FloatField(max_length=254),
        ),
    ]
