# Generated by Django 3.0.7 on 2020-08-10 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0014_parcel_fechacreacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='fechaCreacion',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='parcel',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
