# Generated by Django 3.0.7 on 2020-08-10 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0015_auto_20200810_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='user_created',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcel',
            name='user_updated',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
