# Generated by Django 3.0.7 on 2021-05-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0016_auto_20200810_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='sentinel_instance',
            field=models.CharField(default='96738ec4-8db4-452f-bf50-6ceee33c1c4e', max_length=255),
        ),
    ]
