# Generated by Django 3.0.7 on 2021-05-27 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0017_parcel_sentinel_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='sentinel_instance',
        ),
    ]
