# Generated by Django 3.0.7 on 2021-05-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0018_remove_parcel_sentinel_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='sentinel_instance',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
