# Generated by Django 3.0.7 on 2022-07-28 10:38

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.polygon
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0020_parcel_id_importado'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='area_calc',
            field=models.FloatField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='area_porc',
            field=models.FloatField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='id_productor_importado',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='id_variedad_importado',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='polygon_init',
            field=django.contrib.gis.db.models.fields.PolygonField(default=django.contrib.gis.geos.polygon.Polygon(((0, 0), (0, 10), (10, 10), (0, 10), (0, 0)), ((4, 4), (4, 6), (6, 6), (6, 4), (4, 4))), srid=4326),
        ),
        migrations.AddField(
            model_name='parcel',
            name='productor_importado',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='sigpac_importado',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='variedad_importado',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
