# Generated by Django 3.0.7 on 2022-08-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0021_auto_20220728_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='id_sufijo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
