# Generated by Django 3.0.7 on 2023-09-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0022_parcel_id_sufijo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='is_LYC',
            field=models.BooleanField(default=False),
        ),
    ]
