# Generated by Django 3.0.7 on 2021-06-07 11:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewImagenPro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=254)),
                ('jsonFile', models.CharField(max_length=254)),
                ('xlsxFile', models.CharField(max_length=254)),
                ('capa', models.CharField(max_length=254)),
                ('fechaInicio', models.CharField(max_length=254)),
                ('fechaFin', models.CharField(max_length=254)),
                ('enterprise_id', models.CharField(max_length=255)),
                ('esCooperative', models.BooleanField(default=False)),
                ('user_created', models.CharField(max_length=254)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
