# Generated by Django 3.0.7 on 2021-06-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newimgprocess', '0003_newimagenpro_includeclouds'),
    ]

    operations = [
        migrations.AddField(
            model_name='newimagenpro',
            name='esUnificado',
            field=models.BooleanField(default=False),
        ),
    ]
