# Generated by Django 3.0.7 on 2023-09-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newimgprocess', '0004_newimagenpro_esunificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='newimagenpro',
            name='error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newimagenpro',
            name='estado',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='newimagenpro',
            name='parcelas_fallidas',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
