# Generated by Django 3.0.7 on 2020-08-03 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imgprocess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenpro',
            name='fechas',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
