# Generated by Django 3.0.7 on 2020-08-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgprocess', '0004_auto_20200818_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenpro',
            old_name='jsonFile',
            new_name='imagen',
        ),
    ]
