# Generated by Django 3.0.7 on 2020-08-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgprocess', '0005_auto_20200818_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenpro',
            name='tipo',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
