# Generated by Django 3.0.7 on 2020-08-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgprocess', '0006_imagenpro_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenpro',
            name='tipo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
