# Generated by Django 3.0.7 on 2020-09-25 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imgprocess', '0010_imagenpro_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenpro',
            name='fechaElegida',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
