# Generated by Django 3.0.7 on 2020-09-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgprocess', '0011_imagenpro_fechaelegida'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenpro',
            name='checkDellOtros',
            field=models.BooleanField(default=False),
        ),
    ]
