# Generated by Django 3.0.7 on 2020-09-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgprocess', '0012_imagenpro_checkdellotros'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenpro',
            name='alias',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
