# Generated by Django 3.0.7 on 2020-10-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgprocess', '0013_imagenpro_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenpro',
            name='id_parcelas',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
