# Generated by Django 3.0.7 on 2021-05-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgprocess', '0014_imagenpro_id_parcelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenpro',
            name='esCooperative',
            field=models.BooleanField(default=False),
        ),
    ]
