# Generated by Django 3.0.6 on 2020-05-26 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('roles', '0002_rol_rolid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='rolId',
        ),
        migrations.AddField(
            model_name='rol',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rol',
            name='object_id',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
