# Generated by Django 3.0.6 on 2020-05-26 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_auto_20200526_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='object_id',
        ),
    ]
