# Generated by Django 3.0.6 on 2020-05-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_auto_20200526_1434'),
        ('employees', '0002_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='roles',
            field=models.ManyToManyField(to='roles.Rol'),
        ),
    ]
