# Generated by Django 3.0.6 on 2020-05-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('employees', '0003_employee_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='groups',
            field=models.ManyToManyField(to='groups.Group'),
        ),
    ]
