# Generated by Django 3.0.6 on 2020-05-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20200527_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
