# Generated by Django 3.0.6 on 2020-06-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_auto_20200526_1434'),
        ('groups', '0001_initial'),
        ('employees', '0010_auto_20200604_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='last_name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='a@a.es', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='groups',
            field=models.ManyToManyField(to='groups.Group'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hasRoles',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='roles',
            field=models.ManyToManyField(to='roles.Rol'),
        ),
    ]
