# Generated by Django 4.0.3 on 2022-03-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoistureMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('parcel', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('pix_naranja_total', models.FloatField(blank=True, null=True)),
                ('pix_naranja_porcent', models.FloatField(blank=True, null=True)),
                ('pix_naranja_area_porcent', models.FloatField(blank=True, null=True)),
                ('pix_amarillo_total', models.FloatField(blank=True, null=True)),
                ('pix_amarillo_porcent', models.FloatField(blank=True, null=True)),
                ('pix_amarillo_area_porcent', models.FloatField(blank=True, null=True)),
                ('pix_verde_total', models.FloatField(blank=True, null=True)),
                ('pix_verde_porcent', models.FloatField(blank=True, null=True)),
                ('pix_verde_area_porcent', models.FloatField(blank=True, null=True)),
                ('pix_azul_claro_total', models.FloatField(blank=True, null=True)),
                ('pix_azul_claro_porcent', models.FloatField(blank=True, null=True)),
                ('pix_azul_claro_area_porcent', models.FloatField(blank=True, null=True)),
                ('pix_azul_medio_total', models.FloatField(blank=True, null=True)),
                ('pix_azul_medio_porcent', models.FloatField(blank=True, null=True)),
                ('pix_azul_medio_area_porcent', models.FloatField(blank=True, null=True)),
                ('pix_azul_oscuro_total', models.FloatField(blank=True, null=True)),
                ('pix_azul_oscuro_porcent', models.FloatField(blank=True, null=True)),
                ('pix_azul_oscuro_area_porcent', models.FloatField(blank=True, null=True)),
                ('nubes_porcent', models.FloatField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('nubesImage', models.CharField(blank=True, max_length=255, null=True)),
                ('trueColorImage', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
