# Generated by Django 4.0.3 on 2022-03-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moisturemonitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='MoistureMonitor',
            name='trueColorImage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
