# Generated by Django 3.0.7 on 2020-06-24 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userprofile_enterprise_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='enterprise_id',
        ),
    ]
