# Generated by Django 3.0.7 on 2020-06-24 11:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_userprofile_enterprise_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enterprise_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
