# Generated by Django 3.0.7 on 2020-06-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20200625_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='enterprise_id',
            field=models.CharField(max_length=255),
        ),
    ]
