# Generated by Django 3.0.7 on 2020-06-25 12:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20200625_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='enterprise_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
