# Generated by Django 3.0.7 on 2020-11-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20200625_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cooperative_user',
            field=models.BooleanField(default=False),
        ),
    ]
